version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: intranet-tvs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

  app:
    build: .
    container_name: intranet-tvs-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # Configuraci贸n de la base de datos
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      
      # Configuraci贸n del correo
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_SCHEME: ${MAIL_SCHEME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: ${APP_NAME}
      
      # Configuraci贸n para la creaci贸n del usuario del sistema
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www:delegated
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: intranet-tvs-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - default

volumes:
  db_data:

networks:
  default:
