version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intranet-tvs-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - ":8000"    # El puerto 8000 usado por "php artisan serve"
    depends_on:
      - db
    environment:
      # Conexión a la base de datos (las variables se pasan externamente desde Portainer)
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Configuración del correo
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_SCHEME: ${MAIL_SCHEME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: ${APP_NAME}

      # Configuración para la creación del usuario del Sistema
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  db:
    image: mysql:5.7
    container_name: intranet-tvs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ":3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: intranet-tvs-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8085:80"   # Acceso a phpMyAdmin vía http://localhost:8085
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  dbdata: