version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: intranet-tvs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      default:
        aliases:
          - db

  app:
    build: .
    container_name: intranet-tvs-app
    depends_on:
      - db
    environment:
      # Usa "db" como host para conectarse a la base de datos
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ":8000"
    networks:
      - default

volumes:
  db_data:
